skip_commits:
  files:
  - .travis.yml
  - '**/*.md'
  - .gitignore
  - LICENSE

# version format
version: 1.0.{build}

# Build worker image (VM template)
image: Visual Studio 2015

# build configuration, i.e. Debug, Release, etc.
configuration:
#  - Release
  - PythonModule

for:
-
  matrix:
    only:
      - configuration: PythonModule
  init:
    - set PATH=C:\Python37;%PATH%
    - msbuild /version
    - python --version
  install:
    - if not exist C:\ProgramData\chocolatey\bin\swig.exe choco install swig --version 3.0.12 --yes --limit-output
  before_build:
    - cmd: call script\appveyor\vs_toolset.cmd
  build_script:
    - cmd: cd C:\projects\penguinv\src\python
    - cmd: python setup.py build_ext --inplace

platform:
  - x64
  - x86

# clone directory
clone_folder: C:\projects\penguinv

# scripts to run before build
before_build:
#  - cmd: call script\appveyor\cuda_install.cmd

build_script:
  - set PENGUINV_UNIT_TEST_RUN_COUNT=500
  - cmd: cd C:\projects\penguinv
  - cmd: md build
  - cmd: cd build
  - cmd: if "%platform%"=="x64" cmake -G "Visual Studio 14 2015 Win64" ..
  - cmd: if "%platform%"=="x86" cmake -G "Visual Studio 14 2015" ..
  - cmd: cmake --build . --config %configuration%

test_script:
# OpenCL unit test is excluded as it fails with Exception: Exit code 0xc0000135 on Appveyor
#  - cmd: ctest -C %configuration% -E "unit_tests_opencl|perf_test" --extra-verbose
