skip_commits:
  files:
  - .travis.yml
  - '**/*.md'
  - .gitignore
  - LICENSE

# version format
version: 1.0.{build}

# Build worker image (VM template)
image: Visual Studio 2015

environment:
  matrix:
    - JOB: Release_x86
      configuration: Release
      platform: x86
    - JOB: Release_x64
      configuration: Release
      platform: x64
    - JOB: Python2.7
      PYTHON: "C:\\Python27-x64"
    - JOB: Python3.7
      PYTHON: "C:\\Python37-x64"

for:
-
  matrix:
    only:
      - JOB: Python2.7
      - JOB: Python3.7
  init:
    - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
    - python --version
  install:
    - if not exist C:\ProgramData\chocolatey\bin\swig.exe choco install swig --version 3.0.12 --yes --limit-output -dv
  before_build:
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  build_script:
    - cmd: cd C:\projects\penguinv\src\python
    - cmd: python setup.py build_ext --inplace
  test_script:
    - cmd: cd C:\projects\penguinv\examples\python
    - cmd: python bitmap_operation.py
  cache:
    - C:\ProgramData\chocolatey\bin -> appveyor.yml
    - C:\ProgramData\chocolatey\lib -> appveyor.yml

# clone directory
clone_folder: C:\projects\penguinv

# scripts to run before build
before_build:
  - cmd: call script\appveyor\cuda_install.cmd

install:
  - choco install -y nasm
  - set PATH=%PROGRAMFILES%\nasm;%PATH%

build_script:
  - cmd: if "%APPVEYOR_SCHEDULED_BUILD%" == "True" set PENGUINV_UNIT_TEST_RUN_COUNT=500
  - cmd: cd C:\projects\penguinv
  - cmd: if not exist "build" mkdir "build"
  - cmd: cd build
  - cmd: if "%platform%"=="x64" cmake -G "Visual Studio 14 2015 Win64" ..
  - cmd: if "%platform%"=="x86" cmake -G "Visual Studio 14 2015" ..
  - cmd: cmake --build . --config %configuration%

test_script:
# OpenCL unit test is excluded as it fails with Exception: Exit code 0xc0000135 on Appveyor
  - cmd: ctest -C %configuration% -E "unit_tests_opencl|perf_test|performance_tests_opencl" --extra-verbose

cache:
  - C:/projects/penguinv/build/zlib -> appveyor.yml
  - C:/projects/penguinv/build/jpeg -> appveyor.yml
  - C:/projects/penguinv/build/yasm -> appveyor.yml
  - C:/projects/penguinv/build/png -> appveyor.yml
